// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg2vdI5AzAQ9F7r7mKO73arsOTm9ncZtY',
    appId: '1:880038340902:web:817153310d6bc671f339e7',
    messagingSenderId: '880038340902',
    projectId: 'zeromedixine-76219',
    authDomain: 'zeromedixine-76219.firebaseapp.com',
    storageBucket: 'zeromedixine-76219.firebasestorage.app',
    measurementId: 'G-X16X05GEJ4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2vdI5AzAQ9F7r7mKO73arsOTm9ncZtY',
    appId: '1:880038340902:web:817153310d6bc671f339e7',
    messagingSenderId: '880038340902',
    projectId: 'zeromedixine-76219',
    authDomain: 'zeromedixine-76219.firebaseapp.com',
    storageBucket: 'zeromedixine-76219.firebasestorage.app',
    measurementId: 'G-X16X05GEJ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwV_C5EBSW-5ojHO2aC53xLo13KVji1SA',
    appId: '1:880038340902:ios:b323d5e70474f329f339e7',
    messagingSenderId: '880038340902',
    projectId: 'zeromedixine-76219',
    storageBucket: 'zeromedixine-76219.firebasestorage.app',
    iosBundleId: 'com.zeromedixine.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwV_C5EBSW-5ojHO2aC53xLo13KVji1SA',
    appId: '1:880038340902:ios:b323d5e70474f329f339e7',
    messagingSenderId: '880038340902',
    projectId: 'zeromedixine-76219',
    storageBucket: 'zeromedixine-76219.firebasestorage.app',
    iosBundleId: 'com.zeromedixine.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTl6CrW8hpdi9gLIwagAsOtX_XPBFL3k',
    appId: '1:880038340902:android:d2bbb4a645d7e3c5f339e7',
    messagingSenderId: '880038340902',
    projectId: 'zeromedixine-76219',
    storageBucket: 'zeromedixine-76219.firebasestorage.app',
  );

}